services:
  frontend:
    image: ghcr.io/kb-kkobi/frontend:latest
    container_name: kkobi-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /opt/kkobi/certbot/www:/var/www/certbot:ro